version: '3.8'
services:
  buildkite:
    image: buildkite/agent:ubuntu
    working_dir: /code
    network_mode: "host"
    volumes:
      - .:/code
      - /var/run/docker.sock:/var/run/docker.sock
      - ./builds:/buildkite/builds
      - $HOME/.kube:/root/.kube
      - $HOME/.minikube:$HOME/.minikube
    environment:
      BUILDKITE_AGENT_TOKEN: $BUILDKITE_AGENT_TOKEN
      VOLUME_PATH: $PWD
      DOCKER_TLS_VERIFY: $MINIKUBE_DOCKER_TLS_VERIFY
      DOCKER_HOST: $MINIKUBE_DOCKER_HOST
      DOCKER_CERT_PATH: $MINIKUBE_DOCKER_CERT_PATH
      MINIKUBE_ACTIVE_DOCKERD: $MINIKUBE_MINIKUBE_ACTIVE_DOCKERD
