#!/usr/bin/env bash
echo "Upgrading compose."
path=$(pwd)
echo "Path: $path"
echo "VOLUME_PATH: $VOLUME_PATH"
VOLUME_PATH="${path/\/buildkite/$VOLUME_PATH}"
echo "VOLUME_PATH: $VOLUME_PATH"
rm $(which docker-compose)
curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
