apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    app: flask
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  # Replace with the IP of your minikube node / master node
  externalIPs:
    - 192.168.64.2
  selector:
    app: flask
    tier: backend
