apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: flask
spec:
  selector:
    matchLabels:
      app: flask
      tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: flask
        tier: backend
    spec:
      containers:
        - name: flask
          image: flask:0.6
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_APP
              value: ./backend/server.py
            - name: FLASK_RUN_HOST
              value:  0.0.0.0
            - name: MONGO_HOST
              value: localhost
            - name: MONGO_USERNAME
              value: root
            - name: MONGO_PASSWORD
              value: example
            - name: MONGO_DATABASE
              value: example_dev
            - name: FLASK_ENV
              value: development
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
