apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  # Replace with the IP of your minikube node / master node
  externalIPs:
    - 172.17.0.4
  selector:
    app: nginx
    tier: backend
