#!/usr/bin/env bash
echo "Upgrading compose."
path=$(pwd)
echo "Path: $path"
echo "VOLUME_PATH: $VOLUME_PATH"
VOLUME_PATH="${path/\/buildkite/$VOLUME_PATH}"
echo "VOLUME_PATH: $VOLUME_PATH"
rm $(which docker-compose)
curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose -f

# Install kubectl
# https://kubernetes.io/docs/tasks/tools/install-kubectl/
# Removed `sudo` because running as root.
echo "Installing kubectl"
apt-get update && apt-get install -y apt-transport-https gnupg2
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
apt-get update
apt-get install -y kubectl
