#!/usr/bin/env bash
echo "Upgrading compose."
path=$(pwd)
echo "Path: $path"
echo "VOLUME_PATH: $VOLUME_PATH"
VOLUME_PATH="${path/\/buildkite/$VOLUME_PATH}"
echo "VOLUME_PATH: $VOLUME_PATH"

function install-docker-compose {
  rm $(which docker-compose)
  curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  chmod +x /usr/local/bin/docker-compose
  ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose -f
}

CURRENT_DOCKER_COMPOSE_VERSION=`docker-compose version | grep 'docker-compose version' | cut -c24-29`
TARGET_DOCKER_COMPOSE_VERSION='1.26.2'
if [ "$CURRENT_DOCKER_COMPOSE_VERSION" != "$TARGET_DOCKER_COMPOSE_VERSION" ]; then
  echo "Docker Compose Version: '$CURRENT_DOCKER_COMPOSE_VERSION' does not match target '$TARGET_DOCKER_COMPOSE_VERSION'"
  echo "Installing up to date docker-compose: $TARGET_DOCKER_COMPOSE_VERSION"
  install-docker-compose
else
  echo "Docker Compose Version: '$CURRENT_DOCKER_COMPOSE_VERSION' matches target '$TARGET_DOCKER_COMPOSE_VERSION', not updating."
fi


# Install kubectl
# https://kubernetes.io/docs/tasks/tools/install-kubectl/
# Removed `sudo` because running as root.
function install-kubectl {
  echo "Installing kubectl"
  apt-get update && apt-get install -y apt-transport-https gnupg2
  curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
  apt-get update
  apt-get install -y kubectl
}

if ! command -v kubectl &> /dev/null; then
  echo "`kubectl` could not be found, installing."
  install-kubectl
else
  echo "'kubectl' command found, not installing."
fi
